# permissions for end users to view sohels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sohel-viewer-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - sohels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - sohels/status
  verbs:
  - get
