# permissions for end users to edit sohels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sohel-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - sohels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - sohels/status
  verbs:
  - get
